branches:
  only:
    - master
gemfile:
  - gemfiles/activerecord_4_0.gemfile
  - gemfiles/activerecord_4_1.gemfile
  - gemfiles/activerecord_4_2.gemfile
  - gemfiles/activerecord_5_0.gemfile
  - gemfiles/activerecord_5_1.gemfile
  - gemfiles/activerecord_5_2.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - env: COVERAGE=1
      gemfile: Gemfile
      rvm: 2.5
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
script: bundle exec rspec
